### ISSUE TITLE
Add Azure data

### ISSUE THREAD

**Issue by yolabingo** [yolabingo/django-cloud-provider-zones#1]
- Fetch Azure data as json, save file(s) as `region_data/unparsed_azure*.json`

- Add "azure" to [tasks/constants.py CLOUD_PROVIDERS](https://github.com/yolabingo/django-cloud-provider-zones/blob/main/tasks/constants.py#L3C7-L6C2)

- Create `tasks/azure_update_regions_json` file which converts the unparsed Azure data to

```
region_data/azure_az.json
region_data/azure_provider.json
region_data/azure_region.json
```
using the dataclasses in [tasks/django_model_classes.py](https://github.com/yolabingo/django-cloud-provider-zones/blob/main/tasks/django_model_classes.py) 
use [aws_update_regions_json](https://github.com/yolabingo/django-cloud-provider-zones/blob/main/tasks/aws_update_regions_json) and [gcp_update_regions_json](https://github.com/yolabingo/django-cloud-provider-zones/blob/main/tasks/gcp_update_regions_json)
for reference

The region `short_name` fields for AWS can be derived from the name components provided by the AWS api response. For GCP, we need to generate them using [get_gcp_slug(region)](https://github.com/yolabingo/django-cloud-provider-zones/blob/main/tasks/get_cloud_region_short_names.py#L29)

We'll have to see what azure gives us.

I can show you how to add it to the Django DB from there

**Comment by cobbg** [comment]
Are you planning on using resources in Azure, or are you just trying to be complete in that you're accounting for the three major public cloud providers?

**Comment by yolabingo** [comment]
Not planning to use Azure at all. Mostly an opportunity for others to get their hands on some of this code, as well as checking if/how Azure's region and az names can be stuffed into these structures.

**Comment by yolabingo** [comment]
Complete
